version: '3'

services:
  Rabbit:
    image: rabbitmq:3.12-management
    ports:
      - "15672:15672"
      - "5672:5672"
    container_name: rabbitmq
    stdin_open: true
    tty: true
  Redis:
    image: redis:latest
    ports:
      - "6379:6379"
    container_name: redis
    stdin_open: true
    tty: true